version: '3.8'

services:
  app:
    build:
      context: .
    container_name: todolist
    env_file:
      - .env
    networks:
      - todo-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${POSTGRES_DATABASE}
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:16.1
    container_name: postgres
    networks:
      - todo-network
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

networks:
  todo-network:

volumes:
  db-data:
