spring:
  datasource:
    url: jdbc:postgresql://localhost:7766/todo_DB
    username: todolist_user
    password: 123123@
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 25
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

