spring:
#  cache:
#    type: redis
#    cache-names: redis-cache
  datasource:
    url: jdbc:postgresql://localhost:7766/todo_DB
    username: todolist_user
    password: 123123@
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 25
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: zhenya.slepko@gmail.com
    password: mxcmisxavwbppuqv
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
  graphql:
    graphiql:
      enabled: true
logging:
  level:
    org.springframework.security: trace
    ua.zhenya.todo: debug
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


security:
  jwt:
    secret: fjsdkfjs;dJGFKsdjgfks;jkg&?fjsdkfj;gj"JKASDJGDSKGdjkfs=fjdskf42dajjik9=8
    access: 1800000
    refresh: 2592000000

