--liquibase formatted sql

--changeset Zheka:1
CREATE TABLE projects
(
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(64) NOT NULL,
    color              VARCHAR(16) not null,
    user_id            INT         NOT NULL REFERENCES users (id),
    is_inbox           BOOLEAN     NOT NULL,
    invite_url_enabled BOOLEAN,
    default_role       VARCHAR(16),
    approval_required  BOOLEAN,
    UNIQUE (name, user_id)
);

--changeset Zheka:2
ALTER TABLE tasks
    ADD COLUMN
        project_id INTEGER REFERENCES projects (id) ON DELETE CASCADE;

--changeset Zheka:3
ALTER TABLE users
    RENAME COLUMN username TO email;

--changeset Zheka:4
ALTER TABLE users
    ALTER COLUMN email SET NOT NULL,
    ALTER COLUMN firstname SET NOT NULL,
    ALTER COLUMN password SET NOT NULL;

--changeset Zheka:5
CREATE TABLE user_projects
(
    user_id    INT NOT NULL REFERENCES users (id),
    project_id INT NOT NULL REFERENCES projects (id),
    permission VARCHAR(16),
    PRIMARY KEY (user_id, project_id)
);

--changeset Zheka:6
CREATE TABLE invitations
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id    INT         NOT NULL REFERENCES users (id),
    to_user_id      INT         NOT NULL REFERENCES users (id),
    project_id      INT         NOT NULL REFERENCES projects (id),
    status          VARCHAR(16) NOT NULL,
    permission            VARCHAR(16) not null
);









